#!/bin/sh 
# Create the wastebin on the desktop
mkdir -p ~/Desktop/Wastebin

if [ "$#" = 0 ] ; then
	echo 'Usage: '
	echo '  del filename filename'
	echo '    This is a command to delete files to the wastebin'
elif [ "$#" = 1 ] ; then
	if [ "$1" = -u ] ; then 
		rm ~/Desktop/Wastebin/*
	else
		dirname $(realpath $1) >> "$1"_path
		mv "$1" ~/Desktop/Wastebin/ 
		mv "$1"_path ~/Desktop/Wastebin/
		echo $1 'was moved to Wastebin on Desktop'
	fi
elif [ "$#" = 2 ] ; then
	dirname $(realpath $1) >> "$1"_path
	dirname $(realpath $2) >> "$2"_path
	mv "$1" "$1"_path "$2" "$2"_path ~/Desktop/Wastebin/ 
	echo "$1"' was moved to Wastebin on Desktop'
	echo "$2"' was moved to Wastebin on Desktop'
fi


